travis:
  secure:
    BINSTAR_TOKEN: xkMaUX945nEAKdJqwVykMjwOtCE7MkYiC6raIBk59MZ6D+E0vGla3oln29MEEppyEnUC+vlaniO6JLKp2bos6FqaRg5B3ul69eGwblhjYo4KLdr2k7+ZRokVL1n1PV79BZoPqtfood+bjQAjaIirmV0i5sfTBMF20xkMN1AApMaqb9SgMcbL8eLtu/u0gPyGppXXe+XqpSo2yJAC+d3+PqzvpBPhR5pmykk57Ecsx462L4kXMAEKcxz5VBDgjuAvX1jjQK4F70KYgW7xomK2d8FWa72vUjP4tNmmB8Ed0yylh00zu7ko7AF+kvzbeYLZSK/3JGwbIOix2Ahk/4Jx+3cj1PqcMrn2+HGpJL35USiQtTY8qs3YoT7/PQ42V/rPfNnseFz1ws+AYDMqmgZbAkz6SBePEgtKmrDwZbByGRZuK35XHUakzgMW3hxagXg1vWGQwCWKsT/RlL8Iz1cxyTLfq5H/YZyMsDWbIZRIQdqSUFvTLbBVqZ6J6VpJOICsK3gn4JZDqrINE0C9hi4DWcfjbJ/ZnZG2u7qkG7L9JCNBdCp9NkSmQ8LRiSy8CbYOlo7JSHy8MeuIxWEnfwsyiXMbhhJCEIWngBxiSoLhFsIaO5MOsQXcwxjvXg94ArNaNs+LmKWeHt+YliatZPRoZ/2P+Q/aB9x7NfKa2P8U3x8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
