travis:
  secure:
    BINSTAR_TOKEN: x+TZae9fBQAdKipeX0MGXeAErNuQZoV9ZYR28g6stnlTPXKR8mH2FOFzl/pYcmuhC+UBD6sBCs2AZSMuTSkUFLnNUgEejYazwZkMSqcX9dFB39zoe4pOXdjN3CCGJFNDdYoWg3D4TADRi6MmkrvdCtXzwOoAtRd9aMOhguGNTOQF521tSRoMvkSSH8Af2yX+HS4wAPRsfXptoOd9b0dqeydnOhDjaCXs1twP9z5uoCDSpZKUGAVbDMUErGEHEzfMc/D++LjlncNrUiNKFOP4IyvtXJ96ZyCpc51vkF8mNSU/1fEf7MgBPEz8eg/V/9fik/RN+RhbCKIejodYXULSHegJdvntCloyNVrJXsCZEmkp0A6V1z3h10sP0h/M2OnEhqcL+I/rDIPqlh1Zr6qv2Pcbz8KNJjXwgyv+gBwikJF4wkZ66x/zVbq3Yy+tmBmEk0MBzuOkq+5+OqYzjRPUyshzlNnTkYRQb/vu49f7ZexQ0tHd3cWEze0MCZq4GI6ZSWCjPr+6eAgQOAYA5THd550mPEmb+edutmnBqL+iwazrT5JQa+Ws6WymMbwvrNPOCRQPvZupiP9EseOK21wrwEGn8OKcbkXVnK5BBXhDdwPfxbson/NHh9OK/BDRrUevpOnTygoyLlULzDAAnnDGg7y9O7uVYLl+aAB8PTpaN9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
